version: '3'
services:
    server:
        build:
            context: './server'
            dockerfile: './Dockerfile.dev'
        restart: 'unless-stopped'
        ports:
            - '3000:3000'
        depends_on:
            - db
            - redis
        volumes:
            - './server:/server'
            - 'node_modules:/server/node_modules'
        env_file: './env/server.env'
        working_dir: '/server'
        environment:
            - NODE_ENV
    db:
        image: 'postgres:latest'
        volumes:
            - './postgres:/docker-entrypoint-initdb.d'
            - 'pgdata:/var/lib/postgresql/data'
        env_file: './env/postgres.env'
        ports:
            - '5432:5432'
    redis:
        image: 'redis:alpine'
        env_file: './env/redis.env'
        ports:
            - '6379:6379'
volumes:
    pgdata:
    node_modules:
