version: '2.1'
services:
    web:
        build: .
        ports:
            - '3000:3000'
        environment:
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - db
            - redis
        volumes:
            - .:/backend
    db:
        image: postgres:latest
        env_file: ./envs/postgres.env
        ports:
            - '5432:5432'
    redis:
        image: redis:alpine
        env_file: ./envs/redis.env
        ports:
            - '6379:6379'
