version: '2.1'
services:
    web:
        build: .
        ports:
            - '3000:3000'
        depends_on:
            - db
            - redis
        volumes:
            - .:/backend
    db:
        image: postgres:latest
        env_file: ./envs/postgres.env
        ports:
            - '5432:5432'
        volumes:
            - ./postgres-init:/docker-entrypoint-initdb.d
            - pgdata:/var/lib/postgresql/data
    redis:
        image: redis:alpine
        env_file: ./envs/redis.env
        ports:
            - '6379:6379'
volumes:
    pgdata:
